### ISSUE TITLE
Could you please provide the complete data set?

### ISSUE THREAD

**Issue by Louis-udm** [ENCASEH2020/hatespeech-twitter#1]
I am an NLP master's student. I have been doing offensive detection research recently. I am reading your paper and it is very good. But I think you should provide a complete data set, instead of a list of labeled id, because when the subsequent researchers crawl the tweets,  some tweets will be invalid. As time goes on, we get more and more invalid tweets, then everyone gets a different data set that are not comparable.

So, could you please send the original data set to me? louis.lv.info@gmail.com ,  Thanks a lot!

**Comment by AndyFou** [comment]
Hello Louis, thank you for your interest in our work! The issue you point out is indeed true and has been communicated to us in the past. Because of that we decided to make the content of the tweets available. However, as we state in the README, this part of the dataset is only available under request. 

Since you have requested it though, I am sending you the data at your email. Have a good day! 🙂

**Comment by shirancohen2016** [comment]
Hi,
Is it possible to receive the full dataset with the text? My email is shiran.cohen.2016@gmail.com
Best wishes, 
Shiran

**Comment by dincydavistech** [comment]
Greetings!

I am Dincy Davis, currently doing my master's in "Computational Linguistics", I am planning to do my project on the area of "Abusive Language Detection". When I was search in this topic, I got to read your work and it is very good. It  would really appreciate if you can provide the complete dataset. So could you please send the original dataset to this mail Id:  dincydavis17@gmail.com

Have a nice day.
